# Generated by Django 3.0.2 on 2020-01-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publication_name', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
    ]
