# Generated by Django 3.0.2 on 2020-01-28 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorapp', '0004_editorialboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_no', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_name', models.CharField(blank=True, max_length=100, null=True)),
                ('intro', models.TextField(blank=True, max_length=1000, null=True)),
                ('full_text', models.TextField(blank=True, max_length=1000, null=True)),
                ('issues_pdf', models.FileField(default='default.jpg', upload_to='archive')),
            ],
        ),
        migrations.CreateModel(
            name='CurrentIssues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('issue_no', models.CharField(blank=True, max_length=100, null=True)),
                ('issue_name', models.CharField(blank=True, max_length=100, null=True)),
                ('intro', models.TextField(blank=True, max_length=1000, null=True)),
                ('full_text', models.TextField(blank=True, max_length=1000, null=True)),
                ('issues_pdf', models.FileField(default='default.jpg', upload_to='current_issues')),
            ],
        ),
    ]
