# Generated by Django 3.0.2 on 2020-01-28 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('colorapp', '0005_archive_currentissues'),
    ]

    operations = [
        migrations.AddField(
            model_name='archive',
            name='artical_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='currentissues',
            name='artical_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
